### ISSUE TITLE
Accidentally put in shared tab ID into new tab name input

### ISSUE THREAD

**Issue by ogasser** [xMartin/grouptabs#136] opened 2018-02-22 18:29 UTC
I wanted to open a shared tab using the provided ID. I accidentally put it in the new tab input field resulting in a new tab with a bogus name. Only when going back again I saw the "open shared tab" link.

**Comment by xMartin** [comment] 2018-02-22 22:21
Duplicate of #104 

I bet @jancborchardt told you to file this ;)

**Closed by xMartin** 2018-02-22 22:21 UTC

**Comment by jancborchardt** [comment] 2018-02-25 13:17
> I bet @jancborchardt told you to file this ;)

@xMartin BUSTED :D but it did happen and was annoying.
